name: build revolt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-linux:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Yarn
      run: yarn install
    - name: Build For Linux
      id: build-linux
      run: |
        yarn build:bundle
        yarn build:linux:appimage --publish never
    - name: Pack Build Files
      run: |
        mkdir ~/Revolt-linux
        mv dist/*.AppImage ~/Revolt-linux
        cd ~
        tar -cvf Revolt-linux.tar Revolt-linux/
    - name: Publish Build Files
      uses: actions/upload-artifact@v2
      with:
        path: ~/Revolt-linux.tar
        name: Revolt-linux
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: Install Yarn
      run: yarn install
    - name: Build For Windows
      id: build-windows
      run: |
        yarn build:bundle
        yarn build:windows:appx --publish never
    - name: Pack Build Files and Generate Checksums
      run: |
        mkdir D:\a\desktop\Revolt-windows
        mv D:\a\desktop\desktop\dist\win-unpacked\* D:\a\desktop\Revolt-windows
        cd D:\a\desktop
        tar -cvf Revolt-windows.tar Revolt-windows\*
    - name: Publish Build Files
      uses: actions/upload-artifact@v2
      with:
        path: D:\a\desktop\Revolt-windows.tar
        name: Revolt-windows
  build-macos:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install Yarn
      run: yarn install
    - name: Build For macOS
      run: |
        yarn build:bundle
        yarn build:mac --publish never
    - name: Pack Build Files
      run: |
        mkdir ~/Revolt-macOS
        mv dist/mac-universal/* ~/Revolt-macOS
        cd ~
        tar -cvf Revolt-macOS.tar Revolt-macOS/
    - name: Publish Build Files
      uses: actions/upload-artifact@v2
      with:
        path: ~/Revolt-macOS.tar
        name: Revolt-macOS
